-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 11:07:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_veterinario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_veterinario` ;

-- -----------------------------------------------------
-- Schema db_veterinario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_veterinario` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `db_veterinario` ;

-- -----------------------------------------------------
-- Table `tb_agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_agendamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_agendamento` (
  `id_tb_agendamento` INT NOT NULL AUTO_INCREMENT,
  `dataAgendamento` DATETIME NULL,
  `nomeAnimal` VARCHAR(100) NULL,
  `tipoAnimal` VARCHAR(100) NULL,
  `nomeDono` VARCHAR(200) NULL,
  `telefone` VARCHAR(45) NULL,
  `observacoes` VARCHAR(250) NULL,
  PRIMARY KEY (`id_tb_agendamento`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
